2022-10-10 15:43:41,885 INFO    MainThread:9757 [internal.py:wandb_internal():90] W&B internal server running at pid: 9757, started at: 2022-10-10 15:43:41.885076
2022-10-10 15:43:41,888 INFO    WriterThread:9757 [datastore.py:open_for_write():75] open: /home/student/FedRH/wandb/run-20221010_154341-1gahvelc/run-1gahvelc.wandb
2022-10-10 15:43:41,890 DEBUG   SenderThread:9757 [sender.py:send():232] send: header
2022-10-10 15:43:41,890 DEBUG   SenderThread:9757 [sender.py:send():232] send: run
2022-10-10 15:43:42,484 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: check_version
2022-10-10 15:43:42,485 INFO    SenderThread:9757 [dir_watcher.py:__init__():197] watching files in: /home/student/FedRH/wandb/run-20221010_154341-1gahvelc/files
2022-10-10 15:43:42,485 INFO    SenderThread:9757 [sender.py:_start_run_threads():811] run started: 1gahvelc with start time 1665396821
2022-10-10 15:43:42,485 DEBUG   SenderThread:9757 [sender.py:send():232] send: summary
2022-10-10 15:43:42,485 INFO    SenderThread:9757 [sender.py:_save_file():948] saving file wandb-summary.json with policy end
2022-10-10 15:43:42,486 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: check_version
2022-10-10 15:43:42,927 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: run_start
2022-10-10 15:43:43,488 INFO    Thread-7  :9757 [dir_watcher.py:_on_file_created():244] file/dir created: /home/student/FedRH/wandb/run-20221010_154341-1gahvelc/files/wandb-summary.json
2022-10-10 15:43:44,217 DEBUG   HandlerThread:9757 [meta.py:__init__():35] meta init
2022-10-10 15:43:44,217 DEBUG   HandlerThread:9757 [meta.py:__init__():49] meta init done
2022-10-10 15:43:44,217 DEBUG   HandlerThread:9757 [meta.py:probe():209] probe
2022-10-10 15:43:44,218 DEBUG   HandlerThread:9757 [meta.py:_setup_git():199] setup git
2022-10-10 15:43:44,233 DEBUG   HandlerThread:9757 [meta.py:_setup_git():206] setup git done
2022-10-10 15:43:44,233 DEBUG   HandlerThread:9757 [meta.py:_save_pip():53] save pip
2022-10-10 15:43:44,233 DEBUG   HandlerThread:9757 [meta.py:_save_pip():67] save pip done
2022-10-10 15:43:44,233 DEBUG   HandlerThread:9757 [meta.py:probe():247] probe done
2022-10-10 15:43:44,250 DEBUG   SenderThread:9757 [sender.py:send():232] send: files
2022-10-10 15:43:44,251 INFO    SenderThread:9757 [sender.py:_save_file():948] saving file wandb-metadata.json with policy now
2022-10-10 15:43:44,257 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:43:44,259 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:43:44,488 INFO    Thread-7  :9757 [dir_watcher.py:_on_file_created():244] file/dir created: /home/student/FedRH/wandb/run-20221010_154341-1gahvelc/files/requirements.txt
2022-10-10 15:43:44,489 INFO    Thread-7  :9757 [dir_watcher.py:_on_file_created():244] file/dir created: /home/student/FedRH/wandb/run-20221010_154341-1gahvelc/files/output.log
2022-10-10 15:43:44,489 INFO    Thread-7  :9757 [dir_watcher.py:_on_file_created():244] file/dir created: /home/student/FedRH/wandb/run-20221010_154341-1gahvelc/files/wandb-metadata.json
2022-10-10 15:43:44,716 DEBUG   SenderThread:9757 [sender.py:send():232] send: telemetry
2022-10-10 15:43:46,490 INFO    Thread-7  :9757 [dir_watcher.py:_on_file_modified():257] file/dir modified: /home/student/FedRH/wandb/run-20221010_154341-1gahvelc/files/output.log
2022-10-10 15:43:59,718 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:43:59,718 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:44:19,718 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:44:33,293 ERROR   SenderThread:9757 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 164, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x7f50d4266820>, 'Connection to api.wandb.ai timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f50d4266820>, 'Connection to api.wandb.ai timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/student/.local/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/student/.local/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 140, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/student/.local/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/student/.local/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/student/.local/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f50d4266820>, 'Connection to api.wandb.ai timed out. (connect timeout=10)'))
2022-10-10 15:44:39,719 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:44:50,025 DEBUG   SenderThread:9757 [sender.py:send():232] send: stats
2022-10-10 15:44:50,026 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:44:50,442 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:44:50,521 INFO    Thread-7  :9757 [dir_watcher.py:_on_file_modified():257] file/dir modified: /home/student/FedRH/wandb/run-20221010_154341-1gahvelc/files/config.yaml
2022-10-10 15:44:50,859 DEBUG   SenderThread:9757 [sender.py:send():232] send: stats
2022-10-10 15:44:59,719 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:44:59,720 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:45:19,720 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:45:23,575 DEBUG   SenderThread:9757 [sender.py:send():232] send: stats
2022-10-10 15:45:23,575 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:45:38,958 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:45:38,958 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:45:42,544 DEBUG   SenderThread:9757 [sender.py:send():232] send: stats
2022-10-10 15:45:54,387 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:45:54,387 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:45:55,201 INFO    Thread-11 :9757 [upload_job.py:push():132] Uploaded file /tmp/tmpe0hv1pz9wandb/4yw42l7j-wandb-metadata.json
2022-10-10 15:46:09,754 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:46:09,754 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:46:21,244 DEBUG   SenderThread:9757 [sender.py:send():232] send: stats
2022-10-10 15:46:29,754 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:46:29,755 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:46:49,755 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:46:53,627 DEBUG   SenderThread:9757 [sender.py:send():232] send: stats
2022-10-10 15:46:53,629 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:47:09,756 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:47:17,609 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:47:17,956 DEBUG   SenderThread:9757 [sender.py:send():232] send: stats
2022-10-10 15:47:29,757 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:47:29,757 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:47:42,897 DEBUG   SenderThread:9757 [sender.py:send():232] send: stats
2022-10-10 15:47:45,211 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:47:45,212 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:48:00,638 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:48:00,639 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:48:12,988 DEBUG   SenderThread:9757 [sender.py:send():232] send: stats
2022-10-10 15:48:16,417 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:48:16,417 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:48:31,852 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:48:31,852 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:48:43,067 DEBUG   SenderThread:9757 [sender.py:send():232] send: stats
2022-10-10 15:48:47,341 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:48:47,341 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:49:02,716 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:49:02,716 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:49:13,146 DEBUG   SenderThread:9757 [sender.py:send():232] send: stats
2022-10-10 15:49:18,188 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:49:18,189 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:49:38,189 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:49:38,189 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:49:49,732 DEBUG   SenderThread:9757 [sender.py:send():232] send: stats
2022-10-10 15:49:58,189 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:49:58,190 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:50:18,190 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:50:31,643 ERROR   SenderThread:9757 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 164, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x7f513e775220>, 'Connection to api.wandb.ai timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f513e775220>, 'Connection to api.wandb.ai timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/student/.local/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/student/.local/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 140, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/student/.local/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/student/.local/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/student/.local/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f513e775220>, 'Connection to api.wandb.ai timed out. (connect timeout=10)'))
2022-10-10 15:50:38,191 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:50:55,187 DEBUG   SenderThread:9757 [sender.py:send():232] send: stats
2022-10-10 15:50:55,188 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:50:58,192 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:51:06,857 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:51:18,192 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:51:18,394 DEBUG   SenderThread:9757 [sender.py:send():232] send: stats
2022-10-10 15:51:18,395 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:51:18,793 DEBUG   SenderThread:9757 [sender.py:send():232] send: stats
2022-10-10 15:51:18,794 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:51:34,183 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:51:34,184 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:51:43,591 DEBUG   SenderThread:9757 [sender.py:send():232] send: stats
2022-10-10 15:51:49,540 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:51:49,540 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:52:09,540 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:52:13,393 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:52:13,759 DEBUG   SenderThread:9757 [sender.py:send():232] send: stats
2022-10-10 15:52:28,763 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:52:28,764 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:52:43,767 DEBUG   SenderThread:9757 [sender.py:send():232] send: stats
2022-10-10 15:52:48,764 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:52:48,765 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:53:08,765 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:53:08,765 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:53:13,844 DEBUG   SenderThread:9757 [sender.py:send():232] send: stats
2022-10-10 15:53:24,127 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:53:24,127 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:53:43,922 DEBUG   SenderThread:9757 [sender.py:send():232] send: stats
2022-10-10 15:53:44,127 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:53:44,127 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:54:04,127 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:54:04,128 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:54:14,001 DEBUG   SenderThread:9757 [sender.py:send():232] send: stats
2022-10-10 15:54:19,471 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:54:19,471 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:54:39,472 DEBUG   HandlerThread:9757 [handler.py:handle_request():141] handle_request: stop_status
2022-10-10 15:54:43,141 DEBUG   SenderThread:9757 [sender.py:send_request():246] send_request: stop_status
2022-10-10 15:54:44,090 DEBUG   SenderThread:9757 [sender.py:send():232] send: stats
